### ISSUE TITLE
你好，我在安装过程中黑屏

### ISSUE THREAD

**Issue by Lemon-bule** [geek5nan/Hackintosh-Dell-Vostro-3670#3]
![IMG_3172](https://user-images.githubusercontent.com/48741439/88463110-e9e12a80-cee2-11ea-9274-694a740c52c7.PNG)
![IMG_3184](https://user-images.githubusercontent.com/48741439/88463114-ecdc1b00-cee2-11ea-9a8b-525d6467b925.PNG)
![IMG_3185](https://user-images.githubusercontent.com/48741439/88463115-ee0d4800-cee2-11ea-97ea-2c5ea81941f5.PNG)
[opencore-2019-03-19-115313.txt](https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/files/4976123/opencore-2019-03-19-115313.txt)

**Comment by luvletter2333** [comment]
macOS版本？

**Comment by luvletter2333** [comment]
10.15.5参照这个
https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/issues/1

**Comment by luvletter2333** [comment]
将核显的DeviceProperties更换成这个
```
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>
				AACbPg==
				</data>
				<key>device-id</key>
				<data>
				mz4AAA==
				</data>
				<key>framebuffer-con0-alldata</key>
				<data>
				AQEJAAAIAADHAwAA
				</data>
				<key>framebuffer-con0-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con1-alldata</key>
				<data>
				AgAKAAAIAADHAwAA
				</data>
				<key>framebuffer-con1-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con2-alldata</key>
				<data>
				ADAIAAAEAADHAwAA
				</data>
				<key>framebuffer-con2-enable</key>
				<data>
				AAAAAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-stolenmem</key>
				<data>
				AAAwAQ==
				</data>
				<key>hda-fix</key>
				<string>onboard-1</string>
			</dict>
```

**Comment by Lemon-bule** [comment]
> macOS版本？

10.15.6

**Comment by Lemon-bule** [comment]
> 将核显的DeviceProperties更换成这个
> 
> ```
> 			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
> 			<dict>
> 				<key>AAPL,ig-platform-id</key>
> 				<data>
> 				AACbPg==
> 				</data>
> 				<key>device-id</key>
> 				<data>
> 				mz4AAA==
> 				</data>
> 				<key>framebuffer-con0-alldata</key>
> 				<data>
> 				AQEJAAAIAADHAwAA
> 				</data>
> 				<key>framebuffer-con0-enable</key>
> 				<data>
> 				AQAAAA==
> 				</data>
> 				<key>framebuffer-con1-alldata</key>
> 				<data>
> 				AgAKAAAIAADHAwAA
> 				</data>
> 				<key>framebuffer-con1-enable</key>
> 				<data>
> 				AQAAAA==
> 				</data>
> 				<key>framebuffer-con2-alldata</key>
> 				<data>
> 				ADAIAAAEAADHAwAA
> 				</data>
> 				<key>framebuffer-con2-enable</key>
> 				<data>
> 				AAAAAA==
> 				</data>
> 				<key>framebuffer-patch-enable</key>
> 				<data>
> 				AQAAAA==
> 				</data>
> 				<key>framebuffer-stolenmem</key>
> 				<data>
> 				AAAwAQ==
> 				</data>
> 				<key>hda-fix</key>
> 				<string>onboard-1</string>
> 			</dict>
> ```

我安装的是10.15.6

**Comment by luvletter2333** [comment]
10.15.5开始就有这个问题了好像 换成这个试一下

**Comment by Lemon-bule** [comment]
> 10.15.5开始就有这个问题了好像换成这个试一下

能教我操作一吗,oc还不会操作

**Comment by luvletter2333** [comment]
先看一下OC的官方文档吧
你把你的config.plist发一下 我可以帮你改一下

**Comment by Lemon-bule** [comment]
> 先看一下OC的官方文档吧
> 你把你的config.plist发一下我可以帮你改一下

[EFI.zip](https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/files/4977155/EFI.zip)

好的，感谢

**Comment by luvletter2333** [comment]
[config.plist.zip](https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/files/4977160/config.plist.zip)
把config换掉 试试

**Comment by Lemon-bule** [comment]
> [config.plist.zip](https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/files/4977160/config.plist.zip)
> 把config换掉 试试

[opencore-2020-07-26-083624.txt](https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/files/4977421/opencore-2020-07-26-083624.txt)


![IMG_3189](https://user-images.githubusercontent.com/48741439/88476060-e3e15d00-cf67-11ea-8dda-885899c806a3.JPG)
你好，这是我的配置和报错日志文件
![IMG_3191](https://user-images.githubusercontent.com/48741439/88476081-17bc8280-cf68-11ea-8c05-9c129256a7a9.PNG)

**Comment by Lemon-bule** [comment]
![image](https://user-images.githubusercontent.com/48741439/88477028-45f19080-cf6f-11ea-98e6-1a4913e67436.png)

**Comment by luvletter2333** [comment]
尝试自己Google解决吧

**Comment by Lemon-bule** [comment]
> 尝试自己Google解决吧

好的，多谢解答

**Comment by geek5nan** [comment]
> > 尝试自己Google解决吧
> 
> 好的，多谢解答

问题解决了吗？
