### ISSUE TITLE
How to connect 2 monitor in dell vostro 3670

### ISSUE THREAD

**Issue by bdviett** [geek5nan/Hackintosh-Dell-Vostro-3670#5]
I have just installed the hackintosh for my dell desktop vostro 3670
The device has a separate GTX 710 card with 2 ports: 1 hdmi - 1 dvi
Onboad (3670): 1 hdmi 1 VGA.
Currently insert 1 screen HDMI port on the card.
Would you like a solution to install 2 monitors?
The monitor has only HDMI vs VGA ports
Thanks.

**Comment by geek5nan** [comment]
Let me think about it..

**Solution1** 
Monitor 1: HDMI  --> GTX 710 HDMI
Monitor 2: HDMI --> Onboard HDMI

**Solution2**
GTX 710 HDMI --> Monitor 1: HDMI 
GTX 710 DVI --> DVI to HDMI Adapter  --> Monitor 1: HDMI

**Comment by bdviett** [comment]
> Let me think about it..
> 
> **Solution1**
> Monitor 1: HDMI --> GTX 710 HDMI
> Monitor 2: HDMI --> Onboard HDMI
> 
> **Solution2**
> GTX 710 HDMI --> Monitor 1: HDMI
> GTX 710 DVI --> DVI to HDMI Adapter --> Monitor 2: HDMI

Solution 1: False. I was tried but it isn't working.
I will try solution 2. Thanks for your support :D

**Comment by luvletter2333** [comment]
Does your Hackintosh identify GTX 710 and your iGPU correctly?
Please use Hackintool to check it, and post the screenshot of Hackintool.

If yes, do the HDMI port in GTX 710 and the onboard HDMI port work?

**Comment by bdviett** [comment]
Yes, Hackintosh was identify GTX 710 & UHD 630 onboard
Now I was connected HDMI in GTX => Monitor 1 successs.

When I connect HDMI in mainboard => minitor 2 (HDMI): false (black screen)

**Comment by luvletter2333** [comment]
> Yes, Hackintosh was identify GTX 710 & UHD 630 onboard
> Now I was connected HDMI in GTX => Monitor 1 successs.
> 
> When I connect HDMI in mainboard => minitor 2 (HDMI): false (black screen)

Can you post your screenshot of Hackintool?

**Comment by bdviett** [comment]
What module in hackintool do you want?

**Comment by luvletter2333** [comment]
GPU information in the System tab.
I want to check whether your iGPU is loaded properly.

**Comment by bdviett** [comment]
> GPU information in the System tab.
> I want to check whether your iGPU is loaded properly.

Yes, I'll give you tonight.

**Comment by bdviett** [comment]
> Let me think about it..
> 
> **Solution1**
> Monitor 1: HDMI --> GTX 710 HDMI
> Monitor 2: HDMI --> Onboard HDMI
> 
> **Solution2**
> GTX 710 HDMI --> Monitor 1: HDMI
> GTX 710 DVI --> DVI to HDMI Adapter --> Monitor 2: HDMI

I am sorry to reply late.

Solution 2: It's working !!! Thanks for your support !

**Comment by bdviett** [comment]
@luvletter2333 issues was resolved
.
