### ISSUE TITLE
能无痛升级Big Sur么？

### ISSUE THREAD

**Issue by Nxys** [geek5nan/Hackintosh-Dell-Vostro-3670#6]

**Comment by luvletter2333** [comment]
理论可以

将OC与所有kext全部升级到最新版本
然后对照现有config.plist与dortania，修改一份合适现有版本oc的config

此外，请注意AirportBcrmFixup在Big sur上的改动：
https://github.com/acidanthera/AirportBrcmFixup#please-pay-attention

**Comment by geek5nan** [comment]
此项目已适配 Big Sur 11.0.1 ，替换 [EFI](https://github.com/geek5nan/Hackintosh-Dell-Vostro-3670/releases/tag/11.0.1) 后即可无痛升级。
